### ISSUE TITLE
SLAP can no longer authorize

### ISSUE THREAD

**Issue by Brilliand** [raspopov/SLAP#2]
Since yesterday, SLAP (which I have installed on multiple computers) is failing to complete OpenID authorization.  Based on the debug log, it looks to me like authorization was successful as far as the Second Life website is concerned; my guess is that Linden Labs made a small change to their website that renders SLAP unable to recognize a successful authorization.

**Comment by raspopov** [comment]
Thank you! Should be fixed at 468b08c443f342dd2060ca530147112c0169ce2c.
