### ISSUE TITLE
Failed to complete OpenId login

### ISSUE THREAD

**Issue by potayto98** [raspopov/SLAP#3]
I keep getting this error every time I try to open the application. Even when I uninstall and then re-install the app. It just randomly stopped working one day.
![SLAP error](https://user-images.githubusercontent.com/61862065/101871295-520e7100-3b51-11eb-9729-f909556c99f7.png)

**Comment by raspopov** [comment]
At current time all works fine.

Can you confirm that you can login to SL site successfully via browser using the same user name and password you entered to SLAP?

**Comment by potayto98** [comment]
I just logged in via browser and it seemed to fix the issue. I thought logging into the application would be the only thing that mattered. Thanks for pointing that out.
