### ISSUE TITLE
All offline avatars show an error state

### ISSUE THREAD

**Issue by Brilliand** [raspopov/SLAP#5]
All of my offline friends are showing red rather than gray, as though they aren't on my friends list at all.

Looking at the debug log, it appears the "Friends Widget" page is returning a 404.

**Comment by raspopov** [comment]
Currently I see no issues with site. 🤔 
From time to time LL shutdowns some of site services for maintenance.
But for sure login please to https://my.secondlife.com/ and https://secondlife.com/my/ by browser to exclude login issues, for example Linden Lab asks to refresh F2A authentication.
Thank you! 😎

**Comment by astronaut789** [comment]
Still has issue of friends turning red when logging off, instead of grey. Logging into SL on browser still not fixing issues, please help :(
